---
galaxy_info:
  role_name: freeipa_server
  author: Adrian
  description: Install and configure FreeIPA server on Ubuntu 24.04
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
dependencies: []
