---
- name: Configure /etc/hosts on all nodes
  hosts: all
  become: true

  tasks:
    - name: Add cluster hosts to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.fqdn }} {{ item.short }}"
        state: present
      loop:
        - { ip: "10.0.0.246", fqdn: "control.homelab.lab", short: "control" }
        - { ip: "10.0.0.190", fqdn: "storage-arm.homelab.lab", short: "storage-arm" }
        - { ip: "10.0.0.236", fqdn: "worker1.homelab.lab", short: "worker1" }
        - { ip: "10.0.0.19",  fqdn: "worker2.homelab.lab", short: "worker2" }
        - { ip: "10.0.0.116", fqdn: "worker3.homelab.lab", short: "worker3" }
        - { ip: "10.0.0.71",  fqdn: "login.homelab.lab",   short: "login" }
        - { ip: "10.0.0.104", fqdn: "web1.homelab.lab",    short: "web1" }
