---
galaxy_info:
  role_name: nfs_server
  author: Adrian
  description: Configure NFS server for shared home directories
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
dependencies: []
